---
- hosts: "{{ hosts }}"
  become: true
  #gather_facts: false
  tasks:
  - name: crear el directorio prueba
    file:
      path: /var/tmp/prueba
      state: directory
      owner: ts_ansible
      group: tsysadm
    when: ansible_default_ipv4.address == "192.168.17.101"
