---
- hosts: "{{ hosts }}"
  become: true
  gather_facts: false
  tasks:
  - name: instalo el paquete de apache
    package:
      name: httpd
      state: latest
    tags: install
  - name: levantamos httpd y persistente al reboot
    service:
      name: httpd
      state: started
      enabled: yes
    tags: config
  - name: crear una pagina de inicio
    copy:
      content: "Bienvenido!!!!"
      dest: /var/www/html/index.html
    tags: config
  - name: desintalar apache
    package:
      name: httpd
      state: absent
    tags: [never, uninstall]